/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PerfJavaNode.java
 *
 * Created on Apr 12, 2010, 6:56:47 PM
 */

package cedp.node;

import cetus.exec.Driver;
import cedp.util.AStyleWrapper;
import cedp.util.JcraftWrapper;
import cedp.util.JythonWrapper;
import cedp.util.UtilClipboard;
import cedp.util.UtilFile;
import cedp.util.UtilString;
import cedp.util.UtilTable;
import cedp.util.UtilThread;
import cedp.util.gui.ToolTipTreeNode;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.Transferable;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.table.TableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;
import vpa.interpreter.VpaProgram;

/**
 *
 * @author yim6
 */
public class PerfJavaNode extends SshTemplateDialog implements ClipboardOwner
{
    protected String nodeName;
    protected JcraftWrapper net;
    protected VpaProgram vpaProgram;
    
    /** Creates new form PerfJavaNode */
    public PerfJavaNode() {
        initComponents();
    }

    public PerfJavaNode(String name, VpaProgram vpa, String cfg)
    {
        super(name);
        setTitle("[ceval] Performance Java - " + name);
        initComponents();
        InitConfig(cfg);
        vpaProgram = vpa;
        vpa.BuildCommandTree(cmdTree);
        show();
    }

    public void Launch(String pAddr, int pPort, String pId, String pPwd)
    {
        net = new JcraftWrapper(pAddr, pPort, pId, pPwd, consoleArea);
    }
    
    protected void InitConfig(String fname)
    {
        String buffer = UtilFile.Read(fname);

        StringTokenizer token = new StringTokenizer(buffer + "\n", "\n");
        while (token.hasMoreTokens()) {
            String ln = token.nextToken();

            if(ln.startsWith("#")) // skip comments
                continue;

            StringTokenizer ln_token = new StringTokenizer(ln, ":");

            String first = ln_token.nextToken();
            String last = ln_token.nextToken();

            if(first.equals("benchmark"))
                benchmarkField.setText(last);
            else if(first.equals("home")){
                if(!last.endsWith("/"))
                    last += "/";
                homeField.setText(last);
            }
            else if(first.equals("filefilter")){
                fileFilterField.setText(last);
            }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        consoleArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        cmdTree = new javax.swing.JTree();
        nameField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        progBar = new cedp.util.gui.ProgBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileTable = new javax.swing.JTable();
        cmdField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cmdArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        currDir = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        benchmarkField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        homeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fileFilterField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        attachMenuItem = new javax.swing.JMenuItem();
        installMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[ceval] Performance - Java");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        consoleArea.setBackground(new java.awt.Color(0, 102, 153));
        consoleArea.setColumns(20);
        consoleArea.setEditable(false);
        consoleArea.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        consoleArea.setForeground(new java.awt.Color(255, 255, 255));
        consoleArea.setLineWrap(true);
        consoleArea.setRows(5);
        consoleArea.setTabSize(4);
        consoleArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                consoleAreaKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(consoleArea);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Commands");
        cmdTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        cmdTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmdTreeMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(cmdTree);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setLabel("^Break");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        fileTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Type", "File"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fileTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fileTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(fileTable);

        cmdField.setEditable(false);

        jLabel4.setText("CMD:");

        cmdArea.setColumns(10);
        cmdArea.setRows(5);
        cmdArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmdAreaFocusLost(evt);
            }
        });
        jScrollPane4.setViewportView(cmdArea);

        jLabel5.setText("Browse Files");

        jLabel6.setText("Execute Commands");

        currDir.setColumns(15);
        currDir.setEditable(false);
        currDir.setLineWrap(true);
        currDir.setRows(5);
        jScrollPane5.setViewportView(currDir);

        jToolBar1.setRollover(true);

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jLabel1.setText("Benchmark:");

        jLabel2.setText("Home:");

        jLabel3.setText("File Filter:");

        jLabel7.setText("Console");

        jMenu1.setText("Configuration");

        jMenuItem1.setText("Load a VPA program");
        jMenu1.add(jMenuItem1);

        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenuItem);

        jMenuItem3.setText("Save as ...");
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator2);

        attachMenuItem.setText("Connect to a client");
        attachMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(attachMenuItem);

        installMenuItem.setText("Install client programs");
        installMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                installMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(installMenuItem);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Operation");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(benchmarkField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(fileFilterField, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap(311, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane5, 0, 0, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(87, 87, 87)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdField, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(benchmarkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(homeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(fileFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                            .addComponent(cmdField, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(progBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void UpdateFileList()
    {
        String folder = homeField.getText() + currDir.getText();

        TableModel model = fileTable.getModel();
        UtilTable.DeleteAll(fileTable);

        net.RunCommandBlocked("ls -al " + folder +  " > /tmp/ceval");
        net.FtpBlocked("/tmp/ceval", "ceval", net.FtpGet);
        String buffer = UtilFile.Read("ceval");

        // Build srcTree
        StringTokenizer token = new StringTokenizer(buffer + "\n", "\n");
        while (token.hasMoreTokens()) {
            String ln = token.nextToken();

            StringTokenizer ln_token = new StringTokenizer(ln, " ");
            if(ln_token.countTokens() < 4)
                continue;

            Object obj[] = new Object[2];

            String first = ln_token.nextToken();
            String last = first;
            if(first.startsWith("d"))
                obj[0] = "Folder";
            else
                obj[0] = "File";

            String temp;
            while(ln_token.hasMoreTokens()){
                temp = ln_token.nextToken();
                if(temp.equals("->")){
                    obj[0] = (String)obj[0] + "-Symlink";
                    break; /* symlink */
                }
                last = temp;
            }

            obj[1] = last;
            UtilTable.AddToTable(fileTable, obj, false);
        }
    }

    /*
    protected void UpdateFileList()
    {
        UtilTree.RemoveAll(srcTree);

        net.RunCommandBlocked("find . > /tmp/ceval");
        net.FtpBlocked("/tmp/ceval", "ceval", net.FtpGet);

        String buffer = UtilFile.Read("ceval");

        // Build srcTree
        StringTokenizer token = new StringTokenizer(buffer + "\n", "\n");
        DefaultMutableTreeNode parent;
        boolean check;
        
        while (token.hasMoreTokens()) {
            String ln = token.nextToken();

            if(ln.length()<=2)
                continue;
            
            StringTokenizer ln_token = new StringTokenizer(ln.substring(2), "/");

            parent = (DefaultMutableTreeNode) srcTree.getModel().getRoot();
            while(ln_token.countTokens() > 0){
                String name = ln_token.nextToken();

                check = false;
                
                for(int j=0; j<parent.getChildCount(); j++){
                    if(parent.getChildAt(j).toString().equals(name)){
                        parent = (DefaultMutableTreeNode)parent.getChildAt(j);
                        check = true;
                        break;
                    }
                }

                if(!check){
                    DefaultMutableTreeNode child = new DefaultMutableTreeNode(name);
                    parent.add(child);
                    parent = child;
                }
            }
        }
        UtilTree.ApplyFilter((DefaultMutableTreeNode)srcTree.getModel().getRoot(), fileFilterField.getText());
        
        UtilTree.ExpandAll(srcTree);
    }
     */

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int i;
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension window = getSize();

        setLocation(screen.width/2 - window.width/2, screen.height/2 - window.height/2);

        //jButton4ActionPerformed(null);

        //for(i=0; i<cmdTree.getRowCount(); i++)
        //    cmdTree.expandRow(i);
        // TODO add your handling code here:
        //programTable.getSelectionModel().se
    }//GEN-LAST:event_formWindowOpened

    protected Vector GetFileList(String path)
    {
        Vector  vec = new Vector();
        String  buffer;
        int i;

//        cmdOutputStream.StartMonitor();
        //Thread thread = RunCommand();
        //thread.wait(FtpGet)

        cmdInputStream.AddCommand("ls " + path + " > /tmp/hifi");
        Wait(1000);
        FtpIO("/tmp/hifi", "tmp/filelist", FtpGet);
        buffer = UtilFile.Read("tmp/filelist");
//        buffer = cmdOutputStream.StopMonitor();

        /*
        i = 1;
        while (i < buffer.length()) {
            while (buffer.charAt(i) == buffer.)
        }
        */

        StringTokenizer token = new StringTokenizer(buffer, "\n");
        while (token.hasMoreTokens()) {
            String file = token.nextToken();
            vec.addElement(file);
        }

        //cmdInputStream.AddCommand("./parboil run " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + " cuda default");
        return vec;
    }

    protected Vector InstrGetFiles(String dst)
    {
        // TODO add your handling code here:
        /* 1: get file list */
        String path = baseFolderText.getText() + "benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/src/" + dst + "/";
        Vector fileList = GetFileList(path);
        int i;

        String fileName;
        String path_dst = baseFolderText.getText() + "benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/src/" + dst + "/";
        
        FtpIO(".." + File.separator + "instr" + File.separator + "before" + File.separator + "gpufi.h", path_dst + "gpufi.h", FtpPut);
        UtilFile.Copy(".." + File.separator + "instr" + File.separator + "before" + File.separator + "gpufi.h", "gpufi.h");
//        FtpIO(".." + File.separator + "instr" + File.separator + "before" + File.separator + "gpufi_kernel.cu", path_dst + "gpufi_kernel.cu", FtpPut);

        /* 2: copy the source code from injector to control server */
        for(i=0; i<fileList.size(); i++){
            //fileName = "tmp" + File.separatorChar + fileList.elementAt(i);
            fileName = "" + fileList.elementAt(i);
            if(fileName.equals("gpufi.h") || fileName.equals("gpufi_kernel.cu"))
                continue;
            if(fileName.endsWith(".cu") || fileName.endsWith(".h") || fileName.endsWith(".cpp")){
                FtpIO(path + fileList.elementAt(i), fileName, FtpGet);
            }
        }

        Wait(1000);

        return fileList;
    }

    public class Worker implements Runnable
    {
        Thread  thread;
        protected Vector fileList;

        public Worker(Vector v)
        {
            fileList = v;
            thread = new Thread(this);
            thread.start();
        }

        public void run()
        {
        }
    }

    protected void InstrRunCetus(String folder, Vector fileList)
    {
//        new Worker(fileList);
        int i;
        String fileName;
        String currentPath = "";

        if(fileList == null){
            String path = baseFolderText.getText() + "benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/src/cuda_cetus/";
            fileList = GetFileList(path);
        }

        try{
            currentPath = new java.io.File(".").getCanonicalPath();
            //currentPath = currentPath.substring(0, currentPath.length()-1) + File.pathSeparator;
        } catch(Exception e){
            e.printStackTrace();
        }

        //System.getProperty("user.dir");

        /* 3: run CETUS for FI instr. */
        //String userDir = System.getProperty("user.dir");
        //System.setProperty("user.dir", userDir + File.separatorChar + "tmp");

        for(i=0; i<fileList.size(); i++){
        //for(i=fileList.size()-1; i>=0; i--){
            fileName = "" + fileList.elementAt(i);
            if(fileName.equals("gpufi_kernel.cu"))
                continue;
            if(fileName.endsWith(".cu")){
                String args[] = null;
                System.out.println("Instrment: " + fileName);
                //args[0] = "-cuda-inj";
                if(folder.equals("cuda_fi")){
                    args = new String[2];
                    args[0] = "-fault-injector";
                    args[1] = fileName;
                }
                else if(folder.equals("cuda_ed")){
                    args = new String[2];
                    args[0] = "-error-detector1pt";
                    args[1] = fileName;
                }
                else if(folder.equals("cuda_fied")){
                    args = new String[3];
                    args[0] = "-fault-injector";
                    args[1] = "-error-detector";
                    args[2] = fileName;
                }
                else{
                    args = new String[2];
                    args[0] = "-fault-injector";
                    args[1] = fileName;
                }
                //args[1] = "-expand-all-header";
                //args[4] = "-verbosity";
                //args[2] = "-outdir";

                Driver cetusDriver = new Driver();
                cetusDriver.run(args);
                /* C beautifier for instrumented code */
                AStyleWrapper.Buautifier(fileName, fileName + ".beauty");
                AStyleWrapper.Buautifier("cetus_output" + File.separator + fileName, "cetus_output" + File.separator + fileName + ".beauty");
            }
        }
        //System.setProperty("user.dir", userDir);
    }

    protected void InstrPutFiles(String folder, Vector fileList)
    {
        int i;
        String fileName;
        String path = baseFolderText.getText() + "benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/src/cuda_cetus/";

        if(fileList == null)
            fileList = GetFileList(path);

        /* 4: store the instrumented file back to the injector */
        /* copy all files from cuda_cetus to cuda_fi */
        String path_dst = baseFolderText.getText() + "benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/src/" + folder + "/";
        cmdInputStream.AddCommand("mkdir " + path_dst + " -p");
        cmdInputStream.AddCommand("cp " + path + "/* " + path_dst + " -rf");
        Wait(1000);

        /* overwrite instrumented files */
        for(i=0; i<fileList.size(); i++){
            fileName = "" + fileList.elementAt(i);
            if(fileName.equals("gpufi.h") || fileName.equals("gpufi_kernel.cu"))
                continue;
            //fileName = "tmp" + File.separatorChar + fileList.elementAt(i);
            if(fileName.endsWith(".cu")){
                FtpIO("cetus_output" + File.separator + fileName + ".beauty", path_dst + fileName, FtpPut);
            }
        }
        Wait(1000);

        /* store FI library files */
        //cmdInputStream.AddCommand("rm " + path_dst + File.separator + "/gpufi.h -f");
        FtpIO(".." + File.separator + "instr" + File.separator + folder + File.separator + "gpufi.h", path_dst + "gpufi.h", FtpPut);
        FtpIO(".." + File.separator + "instr" + File.separator + folder + File.separator + "gpufi_kernel.cu", path_dst + "gpufi_kernel.cu", FtpPut);
        //cmdInputStream.AddCommand("touch " + path_dst + File.separator + "/gpufi.h");
    }

    protected void Compile(String folder)
    {
        cmdInputStream.AddCommand("./parboil clean " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0));
        cmdInputStream.AddCommand("./parboil compile " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + " " + folder);
    }

    protected void Profile(String folder, String options)
    {
        String path_dst = baseFolderText.getText() + "benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/src/" + folder + "/";

        FtpIO(".." + File.separator + "instr" + File.separator + folder + File.separator + "gpufi.h", path_dst + "gpufi.h", FtpPut);
        FtpIO(".." + File.separator + "instr" + File.separator + folder + File.separator + "gpufi_kernel.cu", path_dst + "gpufi_kernel.cu", FtpPut);

        Wait(1000);

        cmdInputStream.AddCommand("rm " + baseFolderText.getText() + "benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/fi_profile.txt -f");
        cmdInputStream.AddCommand("echo profile " + options + " > " + baseFolderText.getText() + "benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/fi_cmd.txt");
        cmdInputStream.AddCommand("./parboil run " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + " " + folder + " " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 1));
        cmdInputStream.AddCommand("cat " + baseFolderText.getText() + "benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/fi_profile.txt");
    }

    protected void Exec(String folder)
    {
        cmdInputStream.AddCommand("./parboil run " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + " " + folder + " " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 1));
    }

    protected void GenerateGolden(String folder)
    {
        Exec(folder);
        cmdInputStream.AddCommand("cp " + baseFolderText.getText() + "benchmarks/" +  programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/run/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 1) + "/* " +
                                          baseFolderText.getText() + "benchmarks/" +  programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/output/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 1) + "/* -f");
    }

    protected int fiIndex;
    
    protected void AddFaultCmd(BufferedWriter fout, String cmd)
    {
        try{
            fout.write(cmd + "\n");
        } catch(Exception e){
            e.printStackTrace();
        }

        Object obj[] = new Object[3];

        obj[0] = (Object) (String)("" + fiIndex++);
        obj[1] = (Object) (String)(cmd);
        obj[2] = (Object) (String)("");
        
        UtilTable.AddToTable(fiTable, obj, false);
    }

    protected void ReadCmds()
    {
        String str = "";
        String buf;
        int i;
        fiIndex = 0;

//        fiTable.removeAll();
        UtilTable.DeleteAll(fiTable);
        try{
            BufferedWriter fout = new BufferedWriter(new FileWriter("fi_cmd.txt"));
            String fin = campaignTextArea.getText();
            i = 0;
            while(i<fin.length()){
                str = "";
                while(true){
                    if(i>=fin.length())
                        break;
                    buf = fin.substring(i, i+1);
                    i++;
                    if(buf.equals("\n"))
                        break;
                    str += buf;
                }
                System.out.println("READ CMDS: " + str);
                
                StringTokenizer st = new StringTokenizer(str, " ");
                System.out.println("" + str);
                System.out.println("" + st.countTokens());
                if(st.countTokens() == 10){
                    if(st.nextToken().equals("fi")){
                        int kern_id = UtilString.String2Int(st.nextToken());
                        int instance = UtilString.String2Int(st.nextToken());
                        int var_id = UtilString.String2Int(st.nextToken());
                        int call = UtilString.String2Int(st.nextToken());
                        String mask = st.nextToken();
                        int blk = UtilString.String2Int(st.nextToken());
                        int thread = UtilString.String2Int(st.nextToken());
                        String var_type = st.nextToken();
                        String var_name = st.nextToken();

                        AddFaultCmd(fout, "fi " + kern_id + " " + instance + " " + var_id + " " + (call) + " " + mask + " " + blk + " " + thread + " " + var_type + " " + var_name + "\n");
                    }
                }
            }
            fout.close();
        } catch(Exception e){
            e.printStackTrace();
        }
    }

    protected void Generate(String folder)
    {
        FtpIO(baseFolderText.getText() + "benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/fi_profile.txt", "fi_profile.txt", FtpGet);
        Wait(1000);
        String str = "";
        int i;
        int kern_id = -1;
        String kern_name;
        int instance = -1;
        fiIndex = 0;

        fiTable.removeAll();
        try{
            BufferedWriter fout = new BufferedWriter(new FileWriter("fi_cmd.txt"));
            BufferedReader fin = new BufferedReader(new FileReader("fi_profile.txt"));
            while(fin.ready()){
                str = fin.readLine();
                StringTokenizer st = new StringTokenizer(str, "\t");
                if(st.countTokens() == 4){
                    if(st.nextToken().equals("kernel")){
                        kern_id = UtilString.String2Int(st.nextToken());
                        kern_name = st.nextToken();
                        instance = UtilString.String2Int(st.nextToken());
                        System.out.println("fi " + kern_id + " " + instance + " " + kern_name);
                    }
                }
                if(st.countTokens() == 6){
                    if(st.nextToken().equals("variable")){
                        int var_id = UtilString.String2Int(st.nextToken());
                        String var_name = st.nextToken();
                        int call = UtilString.String2Int(st.nextToken());
                        int loop_id = UtilString.String2Int(st.nextToken());
                        String var_type = st.nextToken();

                        AddFaultCmd(fout, "fi " + kern_id + " " + instance + " " + var_id + " " + (call-1) + " 0x80000000 " + var_type + " " + var_name + "\n");
                        AddFaultCmd(fout, "fi " + kern_id + " " + instance + " " + var_id + " " + (call-1) + " 0x40000000 " + var_type + " " + var_name + "\n");
                        AddFaultCmd(fout, "fi " + kern_id + " " + instance + " " + var_id + " " + (call-1) + " 0x08000000 " + var_type + " " + var_name + "\n");
                        AddFaultCmd(fout, "fi " + kern_id + " " + instance + " " + var_id + " " + (call-1) + " 0x00800000 " + var_type + " " + var_name + "\n");
                        AddFaultCmd(fout, "fi " + kern_id + " " + instance + " " + var_id + " " + (call-1) + " 0x00400000 " + var_type + " " + var_name + "\n");
                        AddFaultCmd(fout, "fi " + kern_id + " " + instance + " " + var_id + " " + (call-1) + " 0x00001000 " + var_type + " " + var_name + "\n");
                        AddFaultCmd(fout, "fi " + kern_id + " " + instance + " " + var_id + " " + (call-1) + " 0x00000001 " + var_type + " " + var_name + "\n");
                        //fiTable.getModel().setValueAt(call, fiIndex, fiIndex);
                    }
                }
            }
            fout.close();
        } catch(Exception e){
            e.printStackTrace();
        }
    }

    public class FiThread implements Runnable
    {
        protected String folder;
        
        public FiThread()
        {
        }

        public void FI_Exec(String f)
        {
            folder = f;
            Thread thread = new Thread(this);
            thread.start();
        }

        public void run()
        {
            String dst = "fi.sh";
            String str = "";
            String id;
            int i;

            try{
                File f = new File(dst);

                if(f.exists())
                    f.delete();

                BufferedWriter fout = new BufferedWriter(new FileWriter(dst));

                String path_dst = baseFolderText.getText() + "benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/src/" + folder + "/";

                //Compile(folder);
                //
                for(i=0; i<fiTable.getRowCount(); i++){
                    id = "result-" + (String)fiTable.getValueAt(i, 0) + ".txt";
                    str = (String) fiTable.getValueAt(i, 1);
                    if(str.endsWith("\n"))
                        str = str.substring(0, str.length()-1);
                    //BufferedReader file = new BufferedReader(new FileReader("fi_cmd.txt"));

                    fout.write("rm -f " + id + "\n");
                    fout.write("echo \"" + str + "\" > benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/fi_cmd.txt" + "\n");
                    fout.write("cat benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/fi_cmd.txt" + "\n");
                    fout.write("./parboil run " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + " " + folder + " " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 1) + " > " + id + "\n");
                    //fout.write("cat " + id + "\n");
                        //cmdInputStream.AddCommand("cat " + baseFolderText.getText() + "benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/fi_profile.txt");
                }
                fout.close();
            } catch(Exception e){
                e.printStackTrace();
            }

            cmdInputStream.AddCommand("rm -f " + dst);
            Wait(1000);
            FtpIO(dst, baseFolderText.getText() + dst, FtpPut);
            Wait(2000);
            cmdInputStream.AddCommand("chmod 755 " + dst);
            cmdInputStream.AddCommand("./" + dst);
        }
    }

    protected void FI_ExecTest(String folder)
    {
        String dst = "fi.sh";
        String str = "";
        String id = "";
        int i;

        try{
            File f = new File(dst);

            if(f.exists())
                f.delete();

            BufferedWriter fout = new BufferedWriter(new FileWriter(dst));

            String path_dst = baseFolderText.getText() + "benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/src/" + folder + "/";

            //Compile(folder);
            //
            id = "result-test.txt";
            str = "fi 0 0 0 0 0x0";

            fout.write("rm -f " + id + "\n");
            fout.write("echo \"" + str + "\" > benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/fi_cmd.txt" + "\n");
            fout.write("cat benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/fi_cmd.txt" + "\n");
            fout.write("./parboil run " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + " " + folder + " " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 1) + " > " + id + "\n");
            fout.close();
        } catch(Exception e){
            e.printStackTrace();
        }

        cmdInputStream.AddCommand("rm -f " + dst);
        Wait(1000);
        FtpIO(dst, baseFolderText.getText() + dst, FtpPut);
        Wait(2000);
        cmdInputStream.AddCommand("chmod 755 " + dst);
        cmdInputStream.AddCommand("./" + dst);
        cmdInputStream.AddCommand("cat " + id);
    }

    protected void ED_Exec(String folder)
    {
        cmdInputStream.AddCommand("./parboil run " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + " cuda " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 1));
        cmdInputStream.AddCommand("./parboil run " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + " " + folder + " " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 1));
    }

    protected void FI_GetFiles(String folder)
    {
        String str = "";
        String id;
        int i;

        for(i=0; i<fiTable.getRowCount(); i++){
            id = "result-" + (String)fiTable.getValueAt(i, 0) + ".txt";
            FtpIO(baseFolderText.getText() + id, id, FtpGet);
        }

        Wait(1000);
    }

    protected void FI_Analysis(String folder)
    {
        String str = "";
        String id;
        int i;
        
        for(i=0; i<fiTable.getRowCount(); i++){
            id = "result-" + (String)fiTable.getValueAt(i, 0) + ".txt";
            str = FileRead(id);
            fiTable.setValueAt((Object)str, i, 3);
            if(str.contains("SDC Detected: 1")){
                fiTable.setValueAt((Object)"Detect-Ctrl", i, 2);
            }
            else if(str.contains("SDC Detected: 2")){
                fiTable.setValueAt((Object)"Detect-Data", i, 2);
            }
            else if(str.contains("Pass")){
                if(str.contains("Injected: 0") || str.contains("injected: 0"))
                    fiTable.setValueAt((Object)"NA", i, 2);
                else
                    fiTable.setValueAt((Object)"Pass", i, 2);
            }
            else if(str.contains("Mismatch")){
                fiTable.setValueAt((Object)"SDC", i, 2);
            }
            else if(str.contains("Run failed")){
                fiTable.setValueAt((Object)"Crash", i, 2);
            }
        }
        
        /*
        try{
            //BufferedReader file = new BufferedReader(new FileReader("fi_cmd.txt"));
            while(file.ready()){
                str = file.readLine();
                cmdInputStream.AddCommand("echo " + str + " > benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/fi_cmd.txt");
                cmdInputStream.AddCommand("./parboil run " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + " " + folder + " " + programTable.getModel().getValueAt(programTable.getSelectedRow(), 1));
                //cmdInputStream.AddCommand("cat " + baseFolderText.getText() + "benchmarks/" + programTable.getModel().getValueAt(programTable.getSelectedRow(), 0) + "/fi_profile.txt");
            }
        } catch(Exception e){
            e.printStackTrace();
        }
        */
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        consoleArea.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    public void lostOwnership(Clipboard clipboard, Transferable contents) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        byte a[] = new byte[1];

        a[0] = 0x3; //;0x18; //0x1b
        cmdInputStream.AddCommand("" + new String(a, 0, 1));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void consoleAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consoleAreaKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar() == 3){ // Ctrl+C
            UtilClipboard.Set(consoleArea.getSelectedText());
        }
        else if(evt.getKeyChar() == 24){ // Ctrl+X
            System.out.println("Ctrl+X is not supported. Please use Ctrl+C");
        }
        else if(evt.getKeyChar() == 22){ // Ctrl+V
            consoleArea.append(UtilClipboard.Get());
        }
        else if(evt.getKeyChar() == 16){ // Ctrl+P
            System.out.println("Ctrl+P is not recognized.");
        }
        else{
            System.out.println("" + (int)(evt.getKeyChar()));
            if(evt.getKeyChar() == 10){ // Enter (CR)
                if(cmdField.getText().length()>0)
                    net.RunCommandBlocked(cmdField.getText());
                cmdField.setText("");
            }
            else if(evt.getKeyChar() == 8){ // Backspace
                cmdField.setText(cmdField.getText().substring(0, cmdField.getText().length()-1));
            }
            else{
                cmdField.setText(cmdField.getText() + evt.getKeyChar());
            }
        }
    }//GEN-LAST:event_consoleAreaKeyTyped

    private void cmdTreeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdTreeMousePressed
        // TODO add your handling code here:
        int selRow = cmdTree.getRowForLocation(evt.getX(), evt.getY());
        TreePath selPath = cmdTree.getPathForLocation(evt.getX(), evt.getY());

        cmdAreaFocusLost(null); /* save the current context of cmdArea as a tooltip */
        
        if(selRow != -1) {
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) selPath.getLastPathComponent();
            
            if(evt.getClickCount() == 1) {
                if(node instanceof ToolTipTreeNode){
                    ToolTipTreeNode tnode = (ToolTipTreeNode) node;
                    cmdArea.setText(tnode.GetToolTipText());
                }
                else
                    cmdArea.setText("");
            }
            else if(evt.getClickCount() == 2) {
                if(node instanceof ToolTipTreeNode && node.getChildCount() == 0){
                    ToolTipTreeNode tnode = (ToolTipTreeNode) node;
                    System.out.println("Jython : " + cmdArea.getText());
                    JythonWrapper.Exec(cmdArea.getText());
                }
            }
        }
    }//GEN-LAST:event_cmdTreeMousePressed

    private void fileTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileTableMousePressed
        // TODO add your handling code here:
        if(fileTable.getSelectedRowCount() != 1)
            return;

        if(evt.getClickCount() == 1) {
        }
        else if(evt.getClickCount() == 2) {
            if(fileTable.getModel().getValueAt(fileTable.getSelectedRow(), 0).toString().startsWith("Folder")){
                String dir = currDir.getText();
                String fname = fileTable.getModel().getValueAt(fileTable.getSelectedRow(), 1).toString();
                if(fname.equals(".")){
                    /* do nothing */
                }
                else if(fname.equals("..")){
                    /* find the second last '/' */
                    StringTokenizer token = new StringTokenizer(dir, "/");
                    if(token.countTokens() == 0){
                        /* do nothing */
                        System.out.println("browsing parent directory of home folder is not supported.");
                    }
                    else if(token.countTokens() == 1){
                        currDir.setText("");
                        UpdateFileList();
                    }
                    else{
                        dir = "";
                        int cnt = token.countTokens();
                        for(int i=0; i<cnt-1; i++){
                            dir += token.nextToken() + "/";
                        }
                        currDir.setText(dir);
                        UpdateFileList();
                    }
                }
                else{
                    dir += fname + "/";
                    currDir.setText(dir);
                    UpdateFileList();
                }
            }
        }
    }//GEN-LAST:event_fileTableMousePressed

    private void attachMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachMenuItemActionPerformed
        // TODO add your handling code here:
        new UtilThread(null){public void run(){
            progBar.Process();

            net.RunCommandBlocked("cd " + homeField.getText());
            UpdateFileList();

            progBar.Done();
        }};
        //        cmdInputStream.AddCommand("source path");
    }//GEN-LAST:event_attachMenuItemActionPerformed

    private void installMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_installMenuItemActionPerformed
        // TODO add your handling code here:
                /* install host side compiler */
        // we use CPP installed by cygwin (change the PATH to /cygwin/bin and
        // copy /cygwin/bin/cpp-3.exe /cygwin/bin/cpp.exe
        // replace the header files (usr/include) by one from Linux (mahler)
    }//GEN-LAST:event_installMenuItemActionPerformed

    private void cmdAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmdAreaFocusLost
        // TODO add your handling code here:
        if(cmdTree == null || cmdTree.getSelectionPath() == null)
            return;

        DefaultMutableTreeNode node = (DefaultMutableTreeNode)cmdTree.getSelectionPath().getLastPathComponent();

        if(node instanceof ToolTipTreeNode && node.getChildCount() == 0){
            ToolTipTreeNode tnode = (ToolTipTreeNode)node;
            tnode.SetToolTipText(cmdArea.getText());
        }
    }//GEN-LAST:event_cmdAreaFocusLost

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
        vpaProgram.Save(cmdTree, null);
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void installButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        // TODO add your handling code here:
                                                 
        // TODO add your handling code here:

    
    }                                             


    /*
    public class CmdInputStream extends InputStream
    {
        Vector vec;
        int pos;
        int count;

        public CmdInputStream()
        {
            vec = new Vector();
            pos = 0;
            count = 0;
        }

        public void AddCommand(String cmd)
        {
            vec.addElement(cmd + "\n");
            count += cmd.length();
        }

        public int available() throws IOException
        {
            return count;
        }

        public int read() throws IOException
        {
            int result = -1;

            if(vec == null)
                return -1;

            while(true){
                if(vec.isEmpty())
                    return -1;

                String cmd = (String)vec.elementAt(0);
                if(pos >= cmd.length()){
                    vec.removeElementAt(0);
                    pos = 0;
                    continue;
                }
                result = cmd.charAt(pos);
                pos++;
                count--;
                break;
            }
            //throw IOException
            return result;
        }

        // an over rided function which does not return -1.
        public int read(byte b[], int off, int len) throws IOException
        {
            if (b == null) {
                throw new NullPointerException();
            } else if (off < 0 || len < 0 || len > b.length - off) {
                throw new IndexOutOfBoundsException();
            } else if (len == 0) {
                return 0;
            }

            int c = read();
            if (c == -1) {
                return 0;
            }
            b[off] = (byte)c;

            int i = 1;
            try {
                for (; i < len ; i++) {
                    c = read();
                    if (c == -1) {
                        break;
                    }
                    b[off + i] = (byte)c;
                }
            } catch (IOException ee) {
            }
            return i;
        }
    }

    public InputStream GetInputStream(final String cmd)
    {
        return new InputStream(){
            String s = cmd;
            int inPtr=0;
            public int read()  //minimum implementation of an InputStream
            {
                if( inPtr >= s.length() )
                    return -1;
                else {
                    inPtr++;
                    return s.charAt(inPtr-1);
                }
            }//read
        };//InputStream
    }//textArea2InputStream

    public class CmdOutputStream extends OutputStream
    {
        String      monitor_buffer;
        boolean     monitor_enable;
        JTextArea   textArea;

        public CmdOutputStream(JTextArea t)
        {
            textArea = t;
            monitor_buffer = "";
            monitor_enable = false;
        }

        public void StartMonitor()
        {
            monitor_enable = true;
            monitor_buffer = "";
        }

        public String StopMonitor()
        {
            monitor_enable = false;
            return monitor_buffer;
        }

        public void write(int b) //minimum implementation of an OutputStream
        {
            String bstr;
            byte[] bs = new byte[1];
            bs[0] = (byte) b;

            bstr = new String(bs);
            textArea.append(bstr);
            textArea.setCaretPosition(textArea.getText().length()-1);
            //AsyncUpdate(bstr);
            if(monitor_enable)
                monitor_buffer += bstr;
        }

        private void AsyncUpdate(final String text)
        {
            SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    textArea.append(text);
                    textArea.setCaretPosition(textArea.getText().length()-1);
                }
            });
        }
    }
    */

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfJavaNode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem attachMenuItem;
    private javax.swing.JTextField benchmarkField;
    private javax.swing.JTextArea cmdArea;
    private javax.swing.JTextField cmdField;
    private javax.swing.JTree cmdTree;
    private javax.swing.JTextArea consoleArea;
    private javax.swing.JTextArea currDir;
    private javax.swing.JTextField fileFilterField;
    private javax.swing.JTable fileTable;
    private javax.swing.JTextField homeField;
    private javax.swing.JMenuItem installMenuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField nameField;
    private cedp.util.gui.ProgBar progBar;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}