/**
 * CEDP: Computer Evaluator for Dependability and Performance
 * This file is distributed under the University of Illinois Open Source
 * License. See LICENSE.TXT for details.
 */

package cedp.login;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 * This is a dialog that obtains user login information. Based on this
 * information, this launches a proper control panel and connects to a selected
 * injector node.
 *
 * @author Keun Soo Yim (yim2012@gmail.com)
 */
public class LoginDialog extends javax.swing.JFrame
{
  /** Creates new form LoginDialog */
  public LoginDialog()
  {
    initComponents();
  }

  public void show()
  {
    super.show();
    Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
    Dimension window = getSize();

    setLocation(screen.width/2 - window.width/2, screen.height/2 - window.height/2);
    setVisible(true);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sessionPanel1 = new SessionPanel(this);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CEDP v1.0");
        setResizable(false);

        jMenu1.setText("Session");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem1.setText("About");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sessionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sessionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /**
  * @param args the command line arguments
  */
  public static void main(String args[])
  {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new LoginDialog().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private cedp.login.SessionPanel sessionPanel1;
    // End of variables declaration//GEN-END:variables
}
